fragment ArticlesParts on Articles {
  __typename
  slug
  titleZh
  titleEn
  date
  coverImage
  tags
  summaryZh
  summaryEn
  bodyZh
  bodyEn
  status
  type
}

fragment WorksParts on Works {
  __typename
  slug
  titleZh
  titleEn
  date
  coverImage
  category
  descriptionZh
  descriptionEn
  detailZh
  detailEn
  images
  published
}

fragment ProfileParts on Profile {
  __typename
  nickname
  introZh
  introEn
  avatar
  bioZh
  bioEn
  github
  xiaohongshu
  weibo
  email
}
